name: MATLAB Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: matlab-actions/setup-matlab@v2.3.1
        with:
          products: >
            Instrument_Control_Toolbox
      - uses: actions/setup-python@v6
        with:
            python-version: '3.13' 
      - uses: matlab-actions/run-build@v2
        with:
          tasks: package
      - uses: actions/upload-artifact@v4
        with:
          name: toolbox
          path: "Palladium DAQ/Release/PalladiumDAQ.mltbx"
